"""add_task_external_id

Revision ID: 0880ca2c0724
Revises: ecf4a26ec98d
Create Date: 2026-03-01 20:51:21.020382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0880ca2c0724'
down_revision: Union[str, Sequence[str], None] = 'ecf4a26ec98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('external_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'external_id')
    # ### end Alembic commands ###
