"""initial_schema

Revision ID: 6cc4abad96cc
Revises: 
Create Date: 2026-03-01 18:10:16.505352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc4abad96cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('is_post_hard_workout', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('tier', sa.Enum('long', 'mid', name='goal_tier'), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'done', 'dropped', name='goal_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('research', 'engineering', 'academic', 'athletic', 'career', 'personal', name='project_category'), nullable=False),
    sa.Column('motivation', sa.String(length=2000), nullable=True),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'done', 'dropped', name='project_status'), nullable=False),
    sa.Column('estimated_hours_remaining', sa.Float(), nullable=False),
    sa.Column('github_repo', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('status', sa.Enum('backlog', 'active', 'in_progress', 'done', 'deferred', name='task_status'), nullable=False),
    sa.Column('cognitive_load', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('manual', 'github', 'gcal', name='task_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('energy_level_at_start', sa.Integer(), nullable=False),
    sa.Column('completion_quality', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=500), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('overridden_by_user', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    op.drop_table('schedule_blocks')
    op.drop_table('learning_records')
    op.drop_table('tasks')
    op.drop_table('projects')
    op.drop_table('goals')
    op.drop_table('energy_profiles')
    # ### end Alembic commands ###
